
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/attachment_db
    username: postgres
    password: 100604
  jpa:
    hibernate:
      ddl-auto: update
upload:
  server:
    folder: D:\upload_file

